name: RCD-MD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Deploying Application
      run: npm install

    - name: BOT Running with retries
      run: |
        max_attempts=99999999999
        attempt=0
        until [ $attempt -ge $max_attempts ]
        do
          npm start && break
          attempt=$((attempt+1))
          echo "Attempt $attempt failed! Retrying in 30s..."
          sleep 30
        done
      continue-on-error: true

    - name: Check if BOT Running step passed
      if: failure()
      run: exit 1
